package modules

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestGenerateStandardOverride_BuildableService(t *testing.T) {
	services := []ServiceBuildInfo{
		{Name: "web", HasBuild: true},
	}
	content, err := GenerateStandardOverride("my-workspace", services, "abc1234", false)
	if err != nil {
		t.Fatalf("failed to generate standard override: %v", err)
	}

	if !strings.Contains(content, "# Generated by rexctl - standard Docker Compose override") {
		t.Errorf("missing header in override file: %s", content)
	}

	var parsed StandardOverride
	if err := yaml.Unmarshal([]byte(content), &parsed); err != nil {
		t.Fatalf("failed to unmarshal generated override: %v", err)
	}

	if parsed.Name != "my-workspace" {
		t.Errorf("expected name 'my-workspace', got '%s'", parsed.Name)
	}

	webSvc, ok := parsed.Services["web"]
	if !ok {
		t.Fatal("expected 'web' service in override")
	}

	if webSvc.ContainerName != "my-workspace-web" {
		t.Errorf("expected container_name 'my-workspace-web', got '%s'", webSvc.ContainerName)
	}

	expectedImage := "rexctl/my-workspace/web:abc1234"
	if webSvc.Image != expectedImage {
		t.Errorf("expected image '%s', got '%s'", expectedImage, webSvc.Image)
	}

	if webSvc.Labels["rexctl.workspace"] != "my-workspace" {
		t.Errorf("expected label rexctl.workspace='my-workspace', got '%s'", webSvc.Labels["rexctl.workspace"])
	}
	if webSvc.Labels["rexctl.commit"] != "abc1234" {
		t.Errorf("expected label rexctl.commit='abc1234', got '%s'", webSvc.Labels["rexctl.commit"])
	}
	if webSvc.Labels["rexctl.dirty"] != "false" {
		t.Errorf("expected label rexctl.dirty='false', got '%s'", webSvc.Labels["rexctl.dirty"])
	}
}

func TestGenerateStandardOverride_NonBuildableService(t *testing.T) {
	// A 3rd party registry image (e.g. mosquitto/redis) without a local build context
	services := []ServiceBuildInfo{
		{Name: "mosquitto", HasBuild: false, Image: "eclipse-mosquitto:latest"},
	}
	content, err := GenerateStandardOverride("test1", services, "ed77c51", false)
	if err != nil {
		t.Fatalf("failed to generate override: %v", err)
	}

	var parsed StandardOverride
	if err := yaml.Unmarshal([]byte(content), &parsed); err != nil {
		t.Fatalf("failed to unmarshal override: %v", err)
	}

	if parsed.Name != "test1" {
		t.Errorf("expected name 'test1', got '%s'", parsed.Name)
	}

	mosq, ok := parsed.Services["mosquitto"]
	if !ok {
		t.Fatal("expected 'mosquitto' service in override")
	}

	if mosq.ContainerName != "test1-mosquitto" {
		t.Errorf("expected container_name 'test1-mosquitto', got '%s'", mosq.ContainerName)
	}

	expectedMosqImage := "rexctl/test1/mosquitto:latest"
	if mosq.Image != expectedMosqImage {
		t.Errorf("expected image override '%s' for non-buildable service, got '%s'", expectedMosqImage, mosq.Image)
	}

	if mosq.Labels["rexctl.workspace"] != "test1" {
		t.Errorf("expected label rexctl.workspace='test1', got '%s'", mosq.Labels["rexctl.workspace"])
	}
}

func TestGenerateStandardOverride_MixedServices(t *testing.T) {
	services := []ServiceBuildInfo{
		{Name: "ros-core", HasBuild: true},
		{Name: "mosquitto", HasBuild: false, Image: "eclipse-mosquitto:latest"},
	}
	content, err := GenerateStandardOverride("robot-ws", services, "9f8e7d6", true)
	if err != nil {
		t.Fatalf("failed to generate override: %v", err)
	}

	var parsed StandardOverride
	if err := yaml.Unmarshal([]byte(content), &parsed); err != nil {
		t.Fatalf("failed to unmarshal override: %v", err)
	}

	if parsed.Name != "robot-ws" {
		t.Errorf("expected name 'robot-ws', got '%s'", parsed.Name)
	}

	ros := parsed.Services["ros-core"]
	if ros.ContainerName != "robot-ws-ros-core" {
		t.Errorf("expected container_name 'robot-ws-ros-core', got '%s'", ros.ContainerName)
	}
	expectedRosImage := "rexctl/robot-ws/ros-core:9f8e7d6-dirty"
	if ros.Image != expectedRosImage {
		t.Errorf("expected ros-core image '%s', got '%s'", expectedRosImage, ros.Image)
	}

	mosq := parsed.Services["mosquitto"]
	if mosq.ContainerName != "robot-ws-mosquitto" {
		t.Errorf("expected container_name 'robot-ws-mosquitto', got '%s'", mosq.ContainerName)
	}
	expectedMosqImage := "rexctl/robot-ws/mosquitto:latest"
	if mosq.Image != expectedMosqImage {
		t.Errorf("expected image '%s' for mosquitto, got '%s'", expectedMosqImage, mosq.Image)
	}
	if mosq.Labels["rexctl.dirty"] != "true" {
		t.Errorf("expected mosquitto dirty label to be 'true'")
	}
}

func TestDetectComposeServicesInfo_ExtractsBuildInfo(t *testing.T) {
	dir := t.TempDir()
	composeYAML := `
services:
  app:
    build: .
  cache:
    image: redis:alpine
  worker:
    build:
      context: ./worker
`
	os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(composeYAML), 0644)

	services := DetectComposeServicesInfo(dir)
	if len(services) != 3 {
		t.Fatalf("expected 3 services, got %d: %v", len(services), services)
	}

	// Sorted: app, cache, worker
	if services[0].Name != "app" || !services[0].HasBuild {
		t.Errorf("expected app with build=true: %+v", services[0])
	}
	if services[1].Name != "cache" || services[1].HasBuild || services[1].Image != "redis:alpine" {
		t.Errorf("expected cache with build=false, image=redis:alpine: %+v", services[1])
	}
	if services[2].Name != "worker" || !services[2].HasBuild {
		t.Errorf("expected worker with build=true: %+v", services[2])
	}
}

func TestWriteStandardOverride_AutoDetectsAndWrites(t *testing.T) {
	dir := t.TempDir()
	composeYAML := `
services:
  api:
    build: .
`
	os.WriteFile(filepath.Join(dir, "docker-compose.yaml"), []byte(composeYAML), 0644)

	err := WriteStandardOverride(dir, "dev-stack", "default_api", "1122334", false)
	if err != nil {
		t.Fatalf("expected WriteStandardOverride to succeed, got: %v", err)
	}

	overrideFile := filepath.Join(dir, "docker-compose.override.yml")
	data, err := os.ReadFile(overrideFile)
	if err != nil {
		t.Fatalf("expected docker-compose.override.yml to exist: %v", err)
	}

	var parsed StandardOverride
	if err := yaml.Unmarshal(data, &parsed); err != nil {
		t.Fatalf("failed to unmarshal written override: %v", err)
	}

	if parsed.Name != "dev-stack" {
		t.Errorf("expected name 'dev-stack', got '%s'", parsed.Name)
	}

	apiSvc, ok := parsed.Services["api"]
	if !ok {
		t.Fatal("expected 'api' service in written override")
	}
	if apiSvc.Image != "rexctl/dev-stack/api:1122334" {
		t.Errorf("expected image 'rexctl/dev-stack/api:1122334', got '%s'", apiSvc.Image)
	}
}
