package modules

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

// StandardOverride represents the standard docker-compose.override.yml structure.
type StandardOverride struct {
	Services map[string]StandardOverrideService `yaml:"services"`
}

// StandardOverrideService represents per-service overrides applied by Docker Compose.
type StandardOverrideService struct {
	Image  string            `yaml:"image,omitempty"`
	Labels map[string]string `yaml:"labels,omitempty"`
}

// ServiceBuildInfo describes whether a service in a compose file has a build context.
type ServiceBuildInfo struct {
	Name     string
	HasBuild bool
}

// GenerateStandardOverride generates standard docker-compose.override.yml content.
// Only services with a local build context get their image name overridden.
func GenerateStandardOverride(workspace string, services []ServiceBuildInfo, commitHash string, isDirty bool) (string, error) {
	override := StandardOverride{
		Services: make(map[string]StandardOverrideService),
	}

	for _, svc := range services {
		svcOverride := StandardOverrideService{
			Labels: map[string]string{
				"rexctl.workspace": workspace,
				"rexctl.service":   svc.Name,
				"rexctl.commit":    commitHash,
				"rexctl.dirty":     fmt.Sprintf("%t", isDirty),
			},
		}

		if svc.HasBuild {
			svcOverride.Image = BuildImageTag(workspace, svc.Name, commitHash, isDirty)
		}

		override.Services[svc.Name] = svcOverride
	}

	data, err := yaml.Marshal(&override)
	if err != nil {
		return "", err
	}

	header := "# Generated by rexctl - standard Docker Compose override\n"
	return header + string(data), nil
}

// DetectComposeServicesInfo inspects any existing compose file in repoDir and extracts services with build info.
func DetectComposeServicesInfo(repoDir string) []ServiceBuildInfo {
	candidates := []string{"docker-compose.yml", "docker-compose.yaml", "compose.yaml", "compose.yml"}
	for _, cand := range candidates {
		data, err := os.ReadFile(filepath.Join(repoDir, cand))
		if err == nil {
			var raw struct {
				Services map[string]struct {
					Build any `yaml:"build"`
				} `yaml:"services"`
			}
			if err := yaml.Unmarshal(data, &raw); err == nil && len(raw.Services) > 0 {
				var result []ServiceBuildInfo
				for name, svc := range raw.Services {
					result = append(result, ServiceBuildInfo{
						Name:     name,
						HasBuild: svc.Build != nil,
					})
				}
				sort.Slice(result, func(i, j int) bool {
					return result[i].Name < result[j].Name
				})
				return result
			}
		}
	}
	return nil
}

// WriteStandardOverride generates and writes docker-compose.override.yml into repoDir.
func WriteStandardOverride(repoDir string, workspace string, defaultServiceName string, commitHash string, isDirty bool) error {
	services := DetectComposeServicesInfo(repoDir)
	if len(services) == 0 {
		// If no compose file found, default to single buildable service
		services = []ServiceBuildInfo{
			{Name: defaultServiceName, HasBuild: true},
		}
	}

	content, err := GenerateStandardOverride(workspace, services, commitHash, isDirty)
	if err != nil {
		return fmt.Errorf("failed to generate standard override: %w", err)
	}

	overridePath := filepath.Join(repoDir, "docker-compose.override.yml")
	return os.WriteFile(overridePath, []byte(content), 0644)
}
