package modules

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"rexctl/config"
	"rexctl/logging"
	"rexctl/structs"
	"strings"
	"sync"
)

func askForConfirmation(prompt string) bool {
	fmt.Printf("%s [y/N]: ", prompt)
	reader := bufio.NewReader(os.Stdin)
	response, err := reader.ReadString('\n')
	if err != nil {
		return false
	}
	response = strings.ToLower(strings.TrimSpace(response))
	return response == "y" || response == "yes"
}

func forceRemoveDir(path string) error {
	err := os.RemoveAll(path)
	if err != nil {
		logging.LogInfo("Permission denied removing '%s' (likely root-owned Docker volumes).", path)
		logging.LogInfo("Elevating to sudo. You may be prompted for your password...")

		cmd := exec.Command("sudo", "rm", "-rf", path)

		cmd.Stdin = os.Stdin
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr

		return cmd.Run()
	}
	return nil
}

func CmdSync(args []string) {
	arg := ""
	if len(args) > 0 {
		arg = args[0]
	}
	stackName := getTargetStack(arg)
	stackDir := filepath.Join(config.WorkspacesDir, stackName)

	if _, err := os.Stat(filepath.Join(stackDir, "rex.yaml")); err != nil {
		Die("Stack manifest not found: %s\nRun 'rexctl create %s' first.", filepath.Join(stackDir, "rex.yaml"), stackName)
	}

	logging.LogInfo("------------------------------------------------------------")
	logging.LogInfo("WARNING: Syncing will rebuild container states for '%s'.", stackName)
	logging.LogInfo("Existing containers will be removed and recreated from the remote repository.")
	logging.LogInfo("------------------------------------------------------------")

	if !askForConfirmation("Are you sure you want to proceed with sync?") {
		logging.LogInfo("Sync aborted.")
		return
	}

	m := parseManifest(stackDir)

	for _, c := range m.Spec.Containers {
		if c.Type == "compose" {
			contDir := filepath.Join(stackDir, c.Name)
			relComposeFile := filepath.Join(c.Name, c.ComposeFile)
			absComposeFile := filepath.Join(stackDir, relComposeFile)

			if _, err := os.Stat(contDir); err == nil {
				if _, err := os.Stat(absComposeFile); os.IsNotExist(err) {
					logging.LogInfo("Container '%s' has missing/invalid setup. Re-cloning...", c.Name)
					if err := forceRemoveDir(contDir); err != nil {
						Die("Failed to clean up corrupted container folder '%s': %v", c.Name, err)
					}
				}
			}
		}
	}

	for _, c := range m.Spec.Containers {
		if c.Type == "compose" {
			contDir := filepath.Join(stackDir, c.Name)
			if _, err := os.Stat(contDir); err == nil {
				output, err := runCmd(contDir, "git", "status", "--porcelain")
				if err != nil {
					Die("Failed to check status for '%s': %v", c.Name, err)
				}
				if output != "" {
					logging.LogInfo("WARNING: Container '%s' has staged, unstaged, or untracked changes.", c.Name)
					if askForConfirmation("Force recreate (destroy local changes and re-clone)?") {
						if err := forceRemoveDir(contDir); err != nil {
							Die("Failed to forcibly remove '%s': %v", c.Name, err)
						}
						logging.LogInfo("Local changes destroyed. Repository will be cloned fresh.")
					} else {
						Die("Aborting sync.")
					}
				}
			}
		}
	}

	var wg sync.WaitGroup
	for _, c := range m.Spec.Containers {
		wg.Add(1)
		go func(c structs.Container) {
			defer wg.Done()
			if c.Type == "compose" {
				contDir := filepath.Join(stackDir, c.Name)

				if _, err := os.Stat(contDir); err != nil {
					logging.LogInfo("Cloning '%s'...", c.Name)
					runCmdStream(stackDir, "git", "clone", "--recurse-submodules", c.Remote, c.Name)
					runCmd(contDir, "git", "checkout", c.Revision)
					runCmd(contDir, "git", "submodule", "update", "--init", "--recursive")
				} else {
					logging.LogInfo("Fetching and checking out '%s'...", c.Name)
					runCmd(contDir, "git", "fetch")
					runCmd(contDir, "git", "checkout", c.Revision)
					runCmd(contDir, "git", "submodule", "update", "--init", "--recursive")
				}

				composeDir := filepath.Dir(filepath.Join(contDir, c.ComposeFile))
				os.MkdirAll(composeDir, 0755)
				envContent := fmt.Sprintf("# Generated by rexctl - DO NOT EDIT MANUALLY\nCOMPOSE_PROJECT_NAME=%s\nREXCTL_IMAGE=rex/%s/%s\n", stackName, stackName, c.Name)
				os.WriteFile(filepath.Join(composeDir, ".env"), []byte(envContent), 0644)

			} else if c.Type == "image" {
				logging.LogInfo("Pulling registry image for '%s'...", c.Name)
				runCmdStream(stackDir, "docker", "pull", c.Remote)
				runCmd(stackDir, "docker", "tag", c.Remote, fmt.Sprintf("rex/%s/%s", stackName, c.Name))
			}
		}(c)
	}
	wg.Wait()

	ValidateStack(stackDir)

	logging.LogInfo("Recreating container states for '%s'...", stackName)
	for _, c := range m.Spec.Containers {
		if c.Type == "compose" {
			relComposeFile := filepath.Join(c.Name, c.ComposeFile)
			absComposeFile := filepath.Join(stackDir, relComposeFile)

			if _, err := os.Stat(absComposeFile); err == nil {
				relOverrideFile := createComposeOverride(stackDir, relComposeFile, stackName)
				composeArgs := []string{"compose", "--project-name", stackName, "-f", relComposeFile}
				if relOverrideFile != "" {
					composeArgs = append(composeArgs, "-f", relOverrideFile)
				}

				rmArgs := append(composeArgs, "down")
				cmd := exec.Command("docker", rmArgs...)
				cmd.Dir = stackDir
				cmd.Run()

				if relOverrideFile != "" {
					os.Remove(filepath.Join(stackDir, relOverrideFile))
				}
			}
		} else if c.Type == "image" {
			containerName := fmt.Sprintf("%s-%s", c.Name, stackName)
			exec.Command("docker", "rm", "-f", containerName).Run()
		}
	}

	if active, found := getActiveStack(); found && active == stackName {
		logging.LogInfo("Stack is currently active, applying new state...")
		CmdStart([]string{stackName})
	}

	logging.LogInfo("Sync complete.")
}
